openapi: 3.0.0
info:
  title: Clientsapp API with Swagger
  description: Clientapp application API documentation with Swagger
  contact:
    name: Juan Ramonda
    email: juanpr@gmail.com
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT.html
  version: 0.0.1
servers:
- url: http://localhost:5000/
  description: Development server
tags:
- name: Client
  description: Client operations
- name: Provider
  description: Provider operations
paths:
  /clients/:
    get:
      tags:
      - Client
      description: Returns all clients from the system
      operationId: clientsGET
      responses:
        "200":
          description: A list of clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
                x-content-type: application/json
              examples:
                clients list:
                  $ref: '#/components/examples/ClientsList'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Client
    post:
      tags:
      - Client
      description: Creates a new client
      operationId: clientsPOST
      requestBody:
        description: Client to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientData'
            examples:
              client:
                $ref: '#/components/examples/ClientData'
      responses:
        "200":
          description: The created client with its ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
              examples:
                new client:
                  $ref: '#/components/examples/Client'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Client
  /clients/{clientId}/:
    put:
      tags:
      - Client
      description: Updates a client
      operationId: clientsClientIdPUT
      parameters:
      - name: clientId
        in: path
        description: Client's ID to use
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Client to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientData'
            examples:
              client:
                $ref: '#/components/examples/ClientData'
      responses:
        "200":
          description: The operation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResult'
              examples:
                operation result:
                  $ref: '#/components/examples/OperationResult'
        "404":
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                client not found:
                  $ref: '#/components/examples/ErrorClientNotFound'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Client
    delete:
      tags:
      - Client
      description: Deletes a client
      operationId: clientsClientIdDELETE
      parameters:
      - name: clientId
        in: path
        description: Client's ID to use
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: The operation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResult'
              examples:
                operation result:
                  $ref: '#/components/examples/OperationResult'
        "404":
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                client not found:
                  $ref: '#/components/examples/ErrorClientNotFound'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Client
  /providers/:
    get:
      tags:
      - Provider
      description: Returns all providers from the system
      operationId: providersGET
      responses:
        "200":
          description: A list of providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
                x-content-type: application/json
              examples:
                clients list:
                  $ref: '#/components/examples/ProvidersList'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Provider
    post:
      tags:
      - Provider
      description: Creates a new provider
      operationId: providersPOST
      requestBody:
        description: Provider to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProviderData'
            examples:
              client:
                $ref: '#/components/examples/ProviderData'
      responses:
        "200":
          description: The created client with its ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'
              examples:
                new client:
                  $ref: '#/components/examples/Provider'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Provider
  /providers/{providerId}/:
    delete:
      tags:
      - Provider
      description: Deletes a provider
      operationId: providersProviderIdDELETE
      parameters:
      - name: providerId
        in: path
        description: Provider's ID to use
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: The operation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResult'
              examples:
                operation result:
                  $ref: '#/components/examples/OperationResult'
        "404":
          description: Provider not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                client not found:
                  $ref: '#/components/examples/ErrorProviderNotFound'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Provider
  /providersbyclient/{clientId}/:
    get:
      tags:
      - Provider
      description: Gets the client's providers
      operationId: providersbyclientClientIdGET
      parameters:
      - name: clientId
        in: path
        description: Client's ID to use
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: The providers IDs list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IdentifiableEntity'
                x-content-type: application/json
              examples:
                client:
                  $ref: '#/components/examples/ProvidersIdsList'
        "404":
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                client not found:
                  $ref: '#/components/examples/ErrorClientNotFound'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Provider
    put:
      tags:
      - Provider
      description: Updates a client's providers list
      operationId: providersbyclientClientIdPUT
      parameters:
      - name: clientId
        in: path
        description: Client's ID to use
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Client's providers Ids
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/IdentifiableEntity'
            examples:
              providers:
                $ref: '#/components/examples/ProvidersIdsList'
      responses:
        "200":
          description: The operation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResult'
              examples:
                operation result:
                  $ref: '#/components/examples/OperationResult'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                client not found:
                  $ref: '#/components/examples/ErrorClientNotFound'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Provider
  /clientsbyprovider/{providerId}/:
    get:
      tags:
      - Provider
      description: Gets the number of clients who have this provider
      operationId: clientsbyproviderProviderIdGET
      parameters:
      - name: providerId
        in: path
        description: Provider's ID to use
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: The number of clients who have this provider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                clients:
                  summary: Number of clients response example
                  value:
                    clients: 100
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              examples:
                server error:
                  $ref: '#/components/examples/ErrorModel'
      x-swagger-router-controller: Provider
components:
  schemas:
    ClientData:
      required:
      - email
      - name
      - phone
      type: object
      properties:
        name:
          type: string
          description: Client's name
        email:
          type: string
          description: Client's email
        phone:
          type: string
          description: Client's phone number
    ProviderData:
      required:
      - name
      type: object
      properties:
        name:
          type: string
          description: Provider's name
    Provider:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
          description: Provider ID.
        name:
          type: string
          description: Provider's name
      description: Identifiable provider
      example:
        name: name
        id: id
    Client:
      required:
      - email
      - id
      - name
      - phone
      type: object
      properties:
        id:
          type: string
          description: Client ID.
        name:
          type: string
          description: Client's name
        email:
          type: string
          description: Client's email
        phone:
          type: string
          description: Client's phone number
      description: Identifiable client
      example:
        phone: phone
        name: name
        id: id
        email: email
    IdentifiableEntity:
      required:
      - id
      type: object
      properties:
        id:
          type: string
          description: Entity ID
      example:
        id: id
    OperationResult:
      required:
      - result
      type: object
      properties:
        result:
          type: string
          description: Operation result
        affectedNumber:
          type: number
          description: Number of documents affected by the operation
      example:
        result: result
        affectedNumber: 0.80082819046101150206595775671303272247314453125
    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        message:
          type: string
          description: Error message
        code:
          type: integer
          description: Error code
    inline_response_200:
      type: object
      properties:
        clients:
          type: number
      example:
        clients: 0.80082819046101150206595775671303272247314453125
  examples:
    ClientData:
      summary: New client example
      value:
        name: John
        email: john@gmail.com
        phone: "305000157"
    Client:
      summary: Client example
      value:
        id: "10"
        name: John
        email: john@gmail.com
        phone: "305000157"
    ClientsList:
      summary: Clients list example
      value:
      - id: "10"
        name: John
        email: john@gmail.com
        phone: "305000157"
      - id: "11"
        name: Paul
        email: paul@gmail.com
        phone: "305000158"
    ProviderData:
      summary: New provider example
      value:
        name: Provider 1
    Provider:
      summary: Provider example
      value:
        id: "1"
        name: Provider 1
    ProvidersList:
      summary: Providers list example
      value:
      - id: "1"
        name: Provider 1
      - id: "2"
        name: Provider 2
    ProvidersIdsList:
      summary: Providers IDs list example
      value:
      - id: "1"
      - id: "2"
    OperationResult:
      summary: Operation result example
      value:
        result: OK
        affectedNumber: 1
    ErrorModel:
      summary: Error model example
      value:
        message: Error connecting with database
        code: 5000
    ErrorClientNotFound:
      summary: Client not found error example
      value:
        message: Client not found
        code: 4040
    ErrorProviderNotFound:
      summary: Provider not found error example
      value:
        message: Provider not found
        code: 4041
    IdentifiableEntity:
      summary: Identifiable entity example
      value:
        id: "10"
